user_panel/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "user_panel"
urlpatterns = [
    path('', views.index, name=""),
    path('createBusiness', views.create_business, name="createBusiness"),
    path('my-businesses', views.my_businesses, name="my-businesses"),
    path('business/<business_name>', views.particular_business, name="business"),
    path('addListing', views.add_listing_page, name="addListing"),

    path('purchase-history', views.purchase_history, name="purchase-history"),
    path('get_user', views.get_user, name="get_user"),
    path('add_new_transaction', views.add_new_transaction,
         name="add_new_transaction"),
    path('notifications', views.notifications, name="notifications"),
    path('dashboard', views.index, name="dashboard"),
    path('all-business', views.all_businesses, name="all-business")

]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls')),
    path('admin-panel/', include('admin_panel.urls')),
    path('user-panel/', include('user_panel.urls')),
]

application/models.py
from django.db import models
from datetime import datetime
import json
from django.contrib.auth.models import User, auth
from django.db import connection
from django.db.models import Sum
from django.db.models.base import ModelBase
from django.db.models.fields import related

# Create your models here.

# python manage.py makemigrations
# python manage.py migrate
# python manage.py runserver


class Business_Owner(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    owner_first_name = models.CharField(max_length=50)
    owner_last_name = models.CharField(max_length=50)
    business_email = models.CharField(max_length=50)
    organization_no = models.CharField(max_length=11, default="None")
    business_telephone = models.CharField(max_length=50)
    status = models.IntegerField(default=0)
    registered_time = models.DateTimeField(default=datetime.now())
    profile_picture = models.ImageField(upload_to="business-owner", null=True)
    #  0 = unseen
    # -1 = rejected
    # 1 = approved

    def get_status(self):
        my_status_dict = {
            0: 'pending',
            -1: 'rejected',
            1: 'approved'
        }
        return my_status_dict[self.status]

    def option_to_create_business(self):
        if self.status == 1:
            if not Business.objects.filter(super_owner=self).exists():
                return True

        return False


class Business(models.Model):
    super_owner = models.ForeignKey(Business_Owner, on_delete=models.CASCADE)
    title_name = models.CharField(max_length=255)
    banner_image = models.ImageField(upload_to='banners')
    categories = models.TextField()
    description = models.TextField()
    features = models.TextField()
    organization_no = models.CharField(default="1541-4541", max_length=15)
    written_address = models.TextField()
    phone_number = models.CharField(max_length=20)
    email_address = models.CharField(max_length=20)
    website_link = models.URLField(max_length=200)
    status = models.IntegerField(default=1)
    # 0 = invisible
    # 1 = pending
    # 2 = active

    def bubbleSort(self, arr):
        n = len(arr)

        # Traverse through all array elements
        for i in range(n):

            # Last i elements are already in place
            for j in range(0, n-i-1):

                # traverse the array from 0 to n-i-1
                # Swap if the element found is greater
                # than the next element
                if arr[j]['total_points_owe'] > arr[j+1]['total_points_owe']:
                    arr[j], arr[j+1] = arr[j+1], arr[j]

    def all_customers(self):
        output = {
            'business_name': self.title_name
        }
        customer_list = []
        total = 0

        all_customers = Transaction.objects.raw(
            f'SELECT * FROM application_transaction where business_id={self.id} group by customer_id')
        for cust in all_customers:
            individual_points = cust.customer.business_transaction_details(
                cust.business)
            total += individual_points

            if individual_points > 0:
                link_element = '''<a class='text-dark' href="admin-panel/buyers/'''+f'{cust.customer.id}'+'''" target="_blank">''' + \
                    f'{cust.customer.user_first_name} {cust.customer.user_last_name}' + '''</a>'''
                customer_dict = {
                    'id': cust.customer.id,
                    'name': link_element,
                    'total_points_owe': round(individual_points, 2)
                }
                customer_list.append(customer_dict)

        self.bubbleSort(customer_list)
        output['customer_list'] = customer_list
        output['total'] = round(total, 2)
        return output

        # all_transaction_query = Transaction.objects.filter(business = self)
        # for transaction in all_transaction_query:
        #     if transaction.customer not in customer_list

    # opening_hours = ....
    # questionnaire = ....
    # price range = ......
    # photo galler = .....

    def get_features(self):
        new_features = json.loads(self.features)
        new_features_list = list(
            map(lambda x: Business_Feature.objects.get(id=int(x)), new_features))
        return new_features_list

    def get_categories(self):
        new_categories = json.loads(self.categories)
        new_categories_list = list(
            map(lambda x: Business_Category.objects.get(id=int(x)), new_categories))
        return new_categories_list

    def link_name(self):
        new_name = self.title_name.replace(" ", "-")
        return new_name + f'-{self.id}'

    def wrapped_text(self, my_limit, text):
        if len(text) > my_limit:
            return text[0: my_limit] + "..."
        return text

    def wrapped_description(self):
        return self.wrapped_text(100, self.description)

    def wrapped_location(self):
        return self.wrapped_text(50, self.written_address)


class Social_media(models.Model):
    # social_media_link = models.TextField(null = True)
    pass


class Business_location(models.Model):
    # location_latitude = models.FloatField(null = True)
    # location_langitude = models.FloatField(null = True)
    pass


class Opening_Hours(models.Model):
    pass


class Questionnaire(models.Model):
    pass


class Price_Range(models.Model):
    pass


class Business_Category(models.Model):
    name = models.CharField(max_length=255)


class Business_Feature(models.Model):
    name = models.CharField(max_length=255)


class BusinessView(models.Model):
    business_id = models.IntegerField()


class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_first_name = models.CharField(max_length=50)
    user_last_name = models.CharField(max_length=50)
    user_email = models.CharField(max_length=50)
    user_telephone = models.CharField(max_length=50)
    user_address = models.CharField(max_length=50)
    user_area_code = models.CharField(max_length=50)
    user_city = models.CharField(max_length=50)
    membership_level = models.IntegerField(default=5)
    registered_time = models.DateTimeField(default=datetime.now())
    is_block = models.BooleanField(default=0)

    def business_transaction_details(self, business):
        TOTAL_POINTS_WON = 0
        POINTS_ACHIEVED = 0
        all_points_get = Points_owe.objects.filter(customer=self)
        for single_point_owe in all_points_get:
            if single_point_owe.transaction_source.business == business:
                TOTAL_POINTS_WON += single_point_owe.credit

        sender_account = Account.objects.get(is_business=business)
        receiver_account = Account.objects.get(is_customer=self)
        filtered_records = PointTransaction.objects.filter(
            FROM=sender_account, TO=receiver_account)
        if filtered_records.exists():
            POINTS_ACHIEVED = filtered_records.aggregate(Sum('points'))[
                'points__sum']

        return TOTAL_POINTS_WON - POINTS_ACHIEVED


class Transaction(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    price = models.FloatField()
    receipt = models.CharField(max_length=255)
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    via_money = models.FloatField(default=0)
    via_points = models.FloatField(default=0)
    current_membership_level = models.IntegerField(default=5)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=datetime.now())

    def __str__(self) -> str:
        return f'Price:{self.price}, Via money: {self.via_money}, Via points: {self.via_points}'

    def get_reward_points(self):
        reward_points = (self.via_money / 100) * self.current_membership_level
        reward_points = round(reward_points, 2)
        return reward_points


class Account(models.Model):
    is_customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, null=True)
    is_business = models.ForeignKey(
        Business, on_delete=models.CASCADE, null=True)
    is_admin = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def create_customer_account(self, customer_object):
        self.is_customer = customer_object
        self.save()

    def create_business_account(self, business_object):
        self.is_business = business_object
        self.save()

    def create_admin_account(self):
        self.is_admin = True
        self.save()


class Transfer(models.Model):

    debit = models.FloatField(default=0)
    credit = models.FloatField(default=0)
    account = models.ForeignKey(
        Account, on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def charge_admin_account(self, quantity):
        admin_account = Account.objects.get(is_admin=True)
        self.account = admin_account
        self.credit = quantity
        self.save()


class Points_owe(models.Model):
    debit = models.FloatField(default=0)
    credit = models.FloatField(default=0)
    transaction_source = models.ForeignKey(
        Transaction, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)


class General_Receiver(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_read = models.BooleanField(default=False)


class Notification(models.Model):
    title = models.CharField(max_length=100)
    TYPE = models.IntegerField(default=1)
    # type dict {
    #   1 = won points
    #   2 = congratz
    # }
    content = models.TextField()
    cust_receiver = models.ForeignKey(
        Customer, on_delete=models.CASCADE, null=True)
    owner_receiver = models.ForeignKey(
        Business_Owner, on_delete=models.CASCADE, null=True)
    general_receivers = models.ManyToManyField(General_Receiver, null=True)

templates/login.html
{% include 'inc/head.inc.html' %}

{% include 'inc/navbar.inc.html' %}

<body style="background-color: #ffffff;">
    <div class="row" style="width: 100%;">
        <div class="col-12 d-flex justify-content-center align-items-center" style="min-height: 90vh">
            <div class="my-form">
                <h3 class="text-info">Login here!</h3>
                <form autocomplete="off" style="text-align:center; margin-top: 30px;" action="login" method="POST">
                    {% csrf_token %}
                    <!-- <i class="material-icons pro">account_circle</i> -->
                    <input class="field form-control" id="email" value="{{email}}" name="email" type="email" placeholder="Email" required>
                    <input class="field form-control" id="passowrd" value="{{password}}" name="password" type="password" placeholder="Password" required>
                    <p id="error" 
                        style="
                            text-align: left; 
                            transition-duration:0.25s;
                            color:#ed4337;"
                        >
                        {% for message in messages %}
                            {{message}}
                        {% endfor %}
                    </p>
                    <button class="btn btn-block btn-info" type="submit">NEXT</button>        
                    <p class="my-4">Never registered before?</p>
                    <a href="{% url 'signup' %}"><button class="btn btn-block btn-secondary" type="button">SIGNUP</button></a>
                </form>

            </div>
        </div>
    </div>    
</body>

</html>

templates/main.html
{% extends 'inc/base.html' %}
{% block content %}
    
{% endblock %}

templates/my-business-list.html
{% extends 'inc/base.html' %}
{% load static %}
{% block classpanel %} panel my-profile{% endblock classpanel %}
{% block content %}

<div id="wrapper-content" class="wrapper-content pt-0 pb-0">
    <div class="page-wrapper d-flex flex-wrap flex-xl-nowrap">
        
        {% include 'user_panel/inc/modals.inc.html' %}
        {% if admin %}
            {% include 'admin_panel/inc/profile-side-panel.inc.html' %}
        {% else %}
            {% include 'user_panel/inc/profile-side-panel.inc.html' %}
        {% endif %}
        <div class="page-container">
            <div class="container-fluid">
                <div class="page-content-wrapper d-flex flex-column">
                    <h2 class="mb-5 text-secondary">{{ page_title }}</h2>
                    <div class="row">
                        {% for business in all_businesses %}

                        <div class="col-lg-4 mb-4 mb-lg-0">
                            
                                
                            <div class="box" style="border-radius: 10px important;">
                                <div class="store card rounded-0 border-0">
                                    <div class="position-relative store-image">
                                        <a>
                                            <img src="media/{{ business.banner_image }}" style="height: 160px;" alt="store 1"
                                                 class="card-img-top rounded-0">
                                        </a>
                                        <div class="image-content position-absolute d-flex align-items-center">
                                            <div class="content-right ml-auto d-flex">
                                                <a href="media/{{ business.banner_image }}"
                                                   class="item viewing"
                                                   data-toggle="tooltip"
                                                   data-placement="top"
                                                   title="Quick view" data-gtf-mfp="true">
                                                    <svg class="icon icon-expand">
                                                        <use xlink:href="#icon-expand"></use>
                                                    </svg>
                                                </a>
                                                <a href="#" class="item marking" data-toggle="tooltip"
                                                   data-placement="top"
                                                   title="Bookmark"><i
                                                        class="fal fa-bookmark"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-body pb-4 border-right border-left">
                                        {% if admin %}
                                            <a href="/admin-panel/business/{{business.link_name}}"
                                            class="card-title h5 text-dark d-inline-block mb-2"><span
                                                    class="letter-spacing-25">{{ business.title_name }}</span></a>
                                        {% else %}
                                            <a href="{% url 'user_panel:business' business_name=business.link_name %}"
                                            class="card-title h5 text-dark d-inline-block mb-2"><span
                                                class="letter-spacing-25">{{ business.title_name }}</span></a>
                                        {% endif %}
                                        <ul class="list-inline store-meta mb-4 font-size-sm d-flex align-items-center flex-wrap">
                                            <li class="list-inline-item"><span
                                                    class="badge badge-success mr-1 d-inline-block">5.0</span><span
                                                    class="number">4 rating</span>
                                            </li>
                                            <li class="list-inline-item separate"></li>
                                            <li class="list-inline-item"><span class="mr-1">From</span><span
                                                    class="text-danger font-weight-semibold">$9.0</span>
                                            </li>
                                            <li class="list-inline-item separate"></li>
                                            <li class="list-inline-item"><span
                                                    class="text-green">Open now!</span>
                                            </li>
                                        </ul>
                                        <div class="media">

                                            {% if business.super_owner.profile_picture %}

                                                <a href="#" class="d-inline-block mr-3"><img
                                                        src="media/{{ business.super_owner.profile_picture }}"
                                                        alt="testimonial" class="rounded-circle">
                                                </a>

                                            {% endif %}

                                            <div class="media-body lh-14 font-size-sm" title="{{ business.description }}">
                                                {{ business.wrapped_description }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer rounded-0 border-top-0 pb-3 pt-0 bg-transparent border-left border-right border-bottom">
                                        <div class="border-top pt-3">
                                                    <span class="d-inline-block mr-1">
                                                        <i class="fal fa-map-marker-alt"></i>
                                                    </span>
                                            <a
                                               class="text-secondary pr-3 text-decoration-none address" title="{{ business.written_address }}">
                                                {{ business.wrapped_location }}      
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>

                        {% endfor %}

                    </div>
                    
                </div>
            </div>
        </div>


    </div>

</div>





{% endblock content %}

templates/notification.html
{% extends 'inc/base.html' %}
{% load static %}
{% block classpanel %} panel my-profile{% endblock classpanel %}
{% block content %}

<div id="wrapper-content" class="wrapper-content pt-0 pb-0">
    <div class="page-wrapper d-flex flex-wrap flex-xl-nowrap">
        
        {% include 'user_panel/inc/modals.inc.html' %}
        {% include 'user_panel/inc/profile-side-panel.inc.html' %}

      

        <div class="page-container">
            <div class="container-fluid">
                <div class="page-content-wrapper d-flex flex-column">
                    <h2 class="mb-5 text-secondary">Notifications</h2>

                    
                    <div class="row">

                        <div class="p-3 mx-3 bg-white" style="width: 100%; border-radius: 10px; border: solid 1px rgb(179, 179, 179);">
                            {% if current_user_as_receiver %}



                            {% endif %}

                            
                            {% if all_notifications or current_user_as_receiver %}

                                {% for my_object in current_user_as_receiver %}
                                    {% for notification in my_object.notification_set.all %}
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="wit-comment-viewer {% if my_object.is_read %}read{% else %}unread{% endif %}-notification">
                                                    <div class="row">
                                                        <div class="col-sm-7 d-flex align-items-center">
                                                            <!-- <img src="{{ notification }}" alt=""> -->
                                                            {{ notification.get_icon | safe }}
                                                            <h5 class="title-card my-0">
                                                                {{ notification.title }}
                                                            </h5>
                                                            {% if not my_object.is_read %}
                                                                <span class="bg-primary radius-100 text-white  mx-2" style="padding: 0px 8px; font-size: 12px;">New</span>
                                                            {% endif %}
                                                        </div>
                    
                                                        <div class="col-sm-5 d-flex justify-content-end">
                                                            <div class="color-primary text-center px-3" style="width: fit-content; border-radius:100px; background-color: rgb(150, 150, 150); color: white; border: solid 1px grey;">
                                                                {{ notification.timestamp }}
                                                            </div>
                                                        </div>
                                                    </div>
                    
                                                    <div class="mt-2">
                                                        {{ notification.content | safe }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    {% endfor %}
                                {% endfor %}

                                {% for notification in all_notifications %}

                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="wit-comment-viewer {% if notification.is_read %}read{% else %}unread{% endif %}-notification">
                                                <div class="row">
                                                    <div class="col-sm-7 d-flex align-items-center">
                                                        <!-- <img src="{{ notification }}" alt=""> -->
                                                        {{ notification.get_icon | safe }}
                                                        <h5 class="title-card my-0">
                                                            {{ notification.title }}
                                                        </h5>
                                                        {% if not notification.is_read %}
                                                            <span class="bg-primary radius-100 text-white  mx-2" style="padding: 0px 8px; font-size: 12px;">New</span>
                                                        {% endif %}
                                                    </div>
                
                                                    <div class="col-sm-5 d-flex justify-content-end">
                                                        <div class="color-primary text-center px-3" style="width: fit-content; border-radius:100px; background-color: rgb(150, 150, 150); color: white; border: solid 1px grey;">
                                                            {{ notification.timestamp }}
                                                        </div>
                                                    </div>
                                                </div>
                
                                                <div class="mt-2">
                                                    {{ notification.content | safe }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                {% endfor %}
                              
                            {% else %}

                              <div class="text-center mt-5">
                                  <div class="alert alert-primary" role="alert">
                                    <h3 class="my-0">No any notification yet!</h3>
                                </div>
                              </div>

                            {% endif %}

                        </div>

                       
                        

                    </div>
                    
                </div>
            </div>
        </div>


    </div>

</div>


<script>
 
</script>


{% endblock content %}

templates/signin.html
{% extends 'inc/base.html' %}
{% load static %}
{% block content %}
    <!-- #header end -->
    <div class="row">
        <div class="col-sm-4"></div>

        <div class="col-sm-4 d-flex align-items-center py-0 pb-5">
            <div class="row" style="width: 100%;">
                <div class="col-12 d-flex justify-content-center align-items-center">
                    <div class="my-form my-5">
                        <h3 class="text-primary">Login here!</h3>

                        <div style="width: 350px;">
                            
                    
                            <div class="alert mt-3 mb-0" id="my-msg" role="alert" style="display: none;">
                            </div>
                         

                            <form autocomplete="off" style="text-align:center; margin-top: 30px;" action="login" method="POST">
                                {% csrf_token %}
                                <!-- <i class="material-icons pro">account_circle</i> -->
                                <input class="field form-control" id="email" value="{{email}}" name="email" type="text" placeholder="Email" required>
                                <input class="field form-control" id="passowrd" value="{{password}}" name="password" type="password" placeholder="Password" required>
                                <p id="error" 
                                    style="
                                        text-align: left; 
                                        transition-duration:0.25s;
                                        color:#ed4337;"
                                    >
                                    {% for message in messages %}
                                        {% ifequal message "Incorrect login details!" %}
                                            {{message}}
                                        {% endifequal %}
                                    {% endfor %}
                                </p>
                                <button class="btn btn-block btn-primary" type="submit">NEXT</button>        
                                <p class="my-4">Never registered before?</p>
                                <a href="{% url 'signup' %}" style="text-decoration: none;"><button class="btn btn-block btn-secondary" type="button">SIGNUP</button></a>
                            </form>

                        </div>

        
                    </div>
                </div>
            </div>  
        </div>

        <div class="col-sm-4"></div>    
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script>
    let myMsg = `{% for message in messages %}
                    {{message}}
                 {% endfor %}`;
   
    if (myMsg.trim() != "") {
        $("#my-msg").css('display', '');
        $("#my-msg").text(myMsg);
        if (myMsg.trim() == "Incorrect login details!") {
            $("#my-msg").addClass("alert-danger");
            $("#my-msg").removeClass("alert-success");
        }else{
            $("#my-msg").addClass("alert-success");
            $("#my-msg").removeClass("alert-danger");
        }
    }

</script>

{% endblock %}